# Generated by Django 4.1.5 on 2023-01-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user',
            new_name='User',
        ),
    ]
